services:
  # Combined app service (Django + Angular via WhiteNoise)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grocery-app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/grocery_db
    depends_on:
      - db
    networks:
      - grocery-network

  # Database service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: grocery-db
    environment:
      POSTGRES_DB: grocery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grocery-network

# Named volumes for persistent data
volumes:
  postgres_data:

# Custom network for service communication
networks:
  grocery-network:
    driver: bridge