# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_remove_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylistitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Custom name for this item in this list', max_length=200),
        ),
    ]